<a href="https://colab.research.google.com/github/arafatro/IntroToDS/blob/main/Practice%20Materials/Week%201/DS_Practice_DataTypes_Matrix_Dictionary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Data Science
## Practice Session — Data Types · Data Matrix · Data Dictionary
**Eötvös Loránd University (ELTE) · Faculty of Informatics**

---
**Instructors:** · Arafat Md Easin  
**Goal:** By the end of this session you will be able to:
- Identify and work with Python and Pandas data types
- Understand the structure of a data matrix
- Build and interpret a data dictionary

> **Tip:** Run each cell with `Shift + Enter` and read the comments carefully before moving on.

---
## Part 0 — Setup & Dataset
We will use the **Student Performance** dataset from the UCI Machine Learning Repository throughout this session.

In [1]:
# Install the UCI repository helper (only needed in Colab)
!pip install ucimlrepo -q

In [2]:
import pandas as pd
import numpy as np
from ucimlrepo import fetch_ucirepo

# Fetch dataset
student_performance = fetch_ucirepo(id=320)

X = student_performance.data.features
y = student_performance.data.targets

# Combine features and targets into one DataFrame
df = pd.concat([X, y], axis=1)

print("Dataset loaded successfully!")
df.head()

Dataset loaded successfully!

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

---
## Part 1 — Python Data Types

Before working with DataFrames, it is essential to understand the **basic Python data types**.  
Every value in a dataset maps back to one of these.

| Python Type | Example | Use in DS |
|---|---|---|
| `int` | `42` | Counts, IDs, discrete scores |
| `float` | `3.14` | Measurements, probabilities |
| `str` | `'male'` | Labels, names, categories |
| `bool` | `True` | Flags, binary features |
| `list` | `[1, 2, 3]` | Collections of values |
| `dict` | `{'age': 20}` | Key-value mappings |

In [3]:
# ── 1.1  Basic Python types ──────────────────────────────────────────

age        = 20          # int
gpa        = 14.5        # float
name       = "Alice"     # str
passed     = True        # bool
grades     = [12, 14, 15, 11]   # list
student    = {"name": "Alice", "age": 20, "passed": True}  # dict

print(type(age),    age)
print(type(gpa),    gpa)
print(type(name),   name)
print(type(passed), passed)
print(type(grades), grades)
print(type(student),student)

<class 'int'> 20
<class 'float'> 14.5
<class 'str'> Alice
<class 'bool'> True
<class 'list'> [12, 14, 15, 11]
<class 'dict'> {'name': 'Alice', 'age': 20, 'passed': True}

In [4]:
# ── 1.2  Type conversion (casting) ───────────────────────────────────
# Sometimes data arrives in the wrong type and must be converted.

score_as_string = "18"          # read from a CSV as text
print(type(score_as_string))    # str — cannot do maths on this!

score_as_int = int(score_as_string)
print(type(score_as_int), score_as_int + 2)   # now it works

# float → int (truncates decimal)
height = 1.78
print(int(height))      # 1  (not rounded, truncated)
print(round(height))    # 2  (rounded)

<class 'str'>
<class 'int'> 20
1
2

In [5]:
# ── 1.3  Pandas dtype vs Python type ─────────────────────────────────
# Pandas uses its own type system on top of Python/NumPy.

# Python type  →  Pandas / NumPy dtype
# int          →  int64
# float        →  float64
# str          →  object
# bool         →  bool
# category     →  category  (special Pandas type — memory efficient)

print("Pandas dtypes of the dataset:")
print(df.dtypes)
print("\nNotice: text columns show as 'object' not 'str'")

Pandas dtypes of the dataset:
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

Notice: text columns show as 'object' not 'str'

### Exercise 1
1. Create a variable `study_hours` with the value `"3"` (as a string).
2. Convert it to an integer and multiply by 60 to get minutes.
3. Print the result and its type.

```python
# Your code here
```

In [ ]:
# Your answer here

---
## Part 2 — The Data Matrix

A **data matrix** is the standard rectangular structure used in data science:

- Each **row** = one observation (student, patient, transaction …)
- Each **column** = one feature / variable
- The intersection = one value

```
         col1    col2    col3
row 0  [  v00     v01     v02  ]
row 1  [  v10     v11     v12  ]
row 2  [  v20     v21     v22  ]
```

In Pandas this is a **DataFrame**.

In [6]:
# ── 2.1  Shape of the data matrix ────────────────────────────────────

print("Shape (rows, columns):", df.shape)
print(f"Number of rows    : {df.shape[0]}")
print(f"Number of columns : {df.shape[1]}")

Shape (rows, columns): (649, 33)
Number of rows    : 649
Number of columns : 33

In [7]:
# ── 2.2  Exploring the matrix ─────────────────────────────────────────

print("── First 5 rows ──")
display(df.head())

print("── Last 5 rows ──")
display(df.tail())

print("── Random sample of 5 rows ──")
display(df.sample(5, random_state=42))

── First 5 rows ──

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

── Last 5 rows ──

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

── Random sample of 5 rows ──

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
220,GP,F,16,U,GT3,A,3,1,services,other,...,2,3,3,2,2,4,2,11,11,12
594,MS,F,18,U,GT3,T,4,4,teacher,teacher,...,4,3,5,1,2,1,0,18,18,18
429,MS,M,16,R,LE3,A,4,4,at_home,other,...,5,3,2,1,3,2,5,10,11,11
72,GP,F,15,R,GT3,T,1,1,other,other,...,3,3,4,2,4,5,2,13,11,11

In [8]:
# ── 2.3  Accessing parts of the matrix ───────────────────────────────

# Single column (returns a Series — a 1D slice of the matrix)
print("── Single column: age ──")
print(df["age"].head())

# Multiple columns (returns a DataFrame)
print("\n── Multiple columns ──")
display(df[["age", "studytime", "G1", "G2", "G3"]].head())

# Single row by index
print("\n── Row at index 0 ──")
print(df.iloc[0])

# Specific cell
print("\n── Value at row 0, column 'age' ──")
print(df.at[0, "age"])

── Single column: age ──
0    18
1    17
2    15
3    15
4    16
Name: age, dtype: int64

── Multiple columns ──

   age  studytime  G1  G2  G3
0   18          2   0  11  11
1   17          2   9  11  11
2   15          2  12  13  12
3   15          3  14  14  14
4   16          2  11  13  13

── Row at index 0 ──
school             GP
sex                 F
age                18
address             U
famsize           GT3
Pstatus             A
Medu                4
Fedu                4
Mjob          at_home
Fjob          teacher
reason         course
guardian       mother
traveltime          2
studytime           2
failures            0
schoolsup         yes
famsup             no
paid               no
activities         no
nursery           yes
higher            yes
internet           no
romantic           no
famrel              4
freetime            3
goout               4
Dalc                1
Walc                1
health              3
absences            4
G1                  0
G2                 11
G3                 11
Name: 0, dtype: object

── Value at row 0, column 'age' ──
18

In [9]:
# ── 2.4  Numerical vs Categorical columns ─────────────────────────────
# Correctly identifying column types is the first step in any analysis.

numerical_cols   = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()

print(f"Numerical columns  ({len(numerical_cols)}):")
print(numerical_cols)

print(f"\nCategorical columns ({len(categorical_cols)}):")
print(categorical_cols)

Numerical columns  (16):
['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Categorical columns (17):
['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

In [11]:
# ── 2.5  Missing values in the matrix ────────────────────────────────
# A missing value (NaN) means no observation was recorded for that cell.

missing_count = df.isnull().sum()
missing_cols  = missing_count[missing_count > 0]

if missing_cols.empty:
    print("No missing values found in this dataset.")
else:
    print("Columns with missing values:")
    print(missing_cols)

# Total missing cells as a percentage
total_cells    = df.shape[0] * df.shape[1]
missing_cells  = df.isnull().sum().sum()
print(f"\nTotal missing cells: {missing_cells} / {total_cells} ({missing_cells/total_cells*100:.2f}%)")

No missing values found in this dataset.

Total missing cells: 0 / 21417 (0.00%)

In [12]:
# ── 2.6  Basic statistics of the matrix ──────────────────────────────

print("── Descriptive statistics (numerical columns) ──")
display(df.describe())

print("\n── Value counts for a categorical column: 'sex' ──")
print(df["sex"].value_counts())

── Descriptive statistics (numerical columns) ──

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

── Value counts for a categorical column: 'sex' ──
sex
F    383
M    266
Name: count, dtype: int64

### Exercise 2
1. How many students scored above 15 in the final grade `G3`? Use boolean indexing.
2. What is the average `studytime` for female students only?

```python
# Hint for Q1:
# df[df["G3"] > 15]

# Hint for Q2:
# df[df["sex"] == "F"]["studytime"].mean()
```

In [ ]:
# Your answer here

---
## Part 3 — Data Dictionary

A **data dictionary** is a structured reference table that documents every column in a dataset.  
It is one of the first things you create in a real project — it helps you and your team understand the data.

A good data dictionary contains at minimum:

| Field | Description |
|---|---|
| Column Name | Name as it appears in the dataset |
| Data Type | Pandas dtype (`int64`, `float64`, `object`, …) |
| Missing Values | Number of NaN cells |
| Unique Values | Number of distinct values |
| Description | What the column represents |

In [13]:
# ── 3.1  Build the data dictionary ───────────────────────────────────

# Pull descriptions from the UCI metadata
variable_descriptions = (
    student_performance.variables
    .set_index("name")["description"]
    .to_dict()
)

data_dict = pd.DataFrame({
    "Column Name"  : df.columns,
    "Data Type"    : df.dtypes.astype(str).values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values" : df.nunique().values,
    "Description"  : [variable_descriptions.get(col, "—") for col in df.columns]
})

display(data_dict)

,Column Name,Data Type,Missing Values,Unique Values,Description
0,school,object,0,2,student's school (binary: 'GP' - Gabriel Perei...
1,sex,object,0,2,student's sex (binary: 'F' - female or 'M' - m...
2,age,int64,0,8,student's age (numeric: from 15 to 22)
3,address,object,0,2,student's home address type (binary: 'U' - urb...
4,famsize,object,0,2,family size (binary: 'LE3' - less or equal to ...
5,Pstatus,object,0,2,parent's cohabitation status (binary: 'T' - li...
6,Medu,int64,0,5,"mother's education (numeric: 0 - none, 1 - pr..."
7,Fedu,int64,0,5,"father's education (numeric: 0 - none, 1 - pr..."
8,Mjob,object,0,5,"mother's job (nominal: 'teacher', 'health' car..."
9,Fjob,object,0,5,"father's job (nominal: 'teacher', 'health' car..."
10,reason,object,0,4,reason to choose this school (nominal: close t...
11,guardian,object,0,3,"student's guardian (nominal: 'mother', 'father..."
12,traveltime,int64,0,4,home to school travel time (numeric: 1 - <15 m...
13,studytime,int64,0,4,"weekly study time (numeric: 1 - <2 hours, 2 - ..."
14,failures,int64,0,4,number of past class failures (numeric: n if 1...
15,schoolsup,object,0,2,extra educational support (binary: yes or no)
16,famsup,object,0,2,family educational support (binary: yes or no)
17,paid,object,0,2,extra paid classes within the course subject (...
18,activities,object,0,2,extra-curricular activities (binary: yes or no)
19,nursery,object,0,2,attended nursery school (binary: yes or no)
20,higher,object,0,2,wants to take higher education (binary: yes or...
21,internet,object,0,2,Internet access at home (binary: yes or no)
22,romantic,object,0,2,with a romantic relationship (binary: yes or no)
23,famrel,int64,0,5,quality of family relationships (numeric: from...
24,freetime,int64,0,5,free time after school (numeric: from 1 - very...
25,goout,int64,0,5,going out with friends (numeric: from 1 - very...
26,Dalc,int64,0,5,workday alcohol consumption (numeric: from 1 -...
27,Walc,int64,0,5,weekend alcohol consumption (numeric: from 1 -...
28,health,int64,0,5,current health status (numeric: from 1 - very ...
29,absences,int64,0,24,number of school absences (numeric: from 0 to 93)
30,G1,int64,0,17,first period grade (numeric: from 0 to 20)
31,G2,int64,0,16,second period grade (numeric: from 0 to 20)
32,G3,int64,0,17,"final grade (numeric: from 0 to 20, output tar..."

In [14]:
# ── 3.2  Enrich the dictionary — add a Category column ───────────────
# We classify each column as Numerical, Categorical, or Binary.

def classify_column(col):
    if df[col].dtype in ["int64", "float64"]:
        if df[col].nunique() == 2:
            return "Binary (Numerical)"
        return "Numerical"
    elif df[col].dtype == "object":
        if df[col].nunique() == 2:
            return "Binary (Categorical)"
        return "Categorical"
    return "Other"

data_dict["Category"] = [classify_column(col) for col in df.columns]

display(data_dict[["Column Name", "Data Type", "Category", "Unique Values", "Description"]])

,Column Name,Data Type,Category,Unique Values,Description
0,school,object,Binary (Categorical),2,student's school (binary: 'GP' - Gabriel Perei...
1,sex,object,Binary (Categorical),2,student's sex (binary: 'F' - female or 'M' - m...
2,age,int64,Numerical,8,student's age (numeric: from 15 to 22)
3,address,object,Binary (Categorical),2,student's home address type (binary: 'U' - urb...
4,famsize,object,Binary (Categorical),2,family size (binary: 'LE3' - less or equal to ...
5,Pstatus,object,Binary (Categorical),2,parent's cohabitation status (binary: 'T' - li...
6,Medu,int64,Numerical,5,"mother's education (numeric: 0 - none, 1 - pr..."
7,Fedu,int64,Numerical,5,"father's education (numeric: 0 - none, 1 - pr..."
8,Mjob,object,Categorical,5,"mother's job (nominal: 'teacher', 'health' car..."
9,Fjob,object,Categorical,5,"father's job (nominal: 'teacher', 'health' car..."
10,reason,object,Categorical,4,reason to choose this school (nominal: close t...
11,guardian,object,Categorical,3,"student's guardian (nominal: 'mother', 'father..."
12,traveltime,int64,Numerical,4,home to school travel time (numeric: 1 - <15 m...
13,studytime,int64,Numerical,4,"weekly study time (numeric: 1 - <2 hours, 2 - ..."
14,failures,int64,Numerical,4,number of past class failures (numeric: n if 1...
15,schoolsup,object,Binary (Categorical),2,extra educational support (binary: yes or no)
16,famsup,object,Binary (Categorical),2,family educational support (binary: yes or no)
17,paid,object,Binary (Categorical),2,extra paid classes within the course subject (...
18,activities,object,Binary (Categorical),2,extra-curricular activities (binary: yes or no)
19,nursery,object,Binary (Categorical),2,attended nursery school (binary: yes or no)
20,higher,object,Binary (Categorical),2,wants to take higher education (binary: yes or...
21,internet,object,Binary (Categorical),2,Internet access at home (binary: yes or no)
22,romantic,object,Binary (Categorical),2,with a romantic relationship (binary: yes or no)
23,famrel,int64,Numerical,5,quality of family relationships (numeric: from...
24,freetime,int64,Numerical,5,free time after school (numeric: from 1 - very...
25,goout,int64,Numerical,5,going out with friends (numeric: from 1 - very...
26,Dalc,int64,Numerical,5,workday alcohol consumption (numeric: from 1 -...
27,Walc,int64,Numerical,5,weekend alcohol consumption (numeric: from 1 -...
28,health,int64,Numerical,5,current health status (numeric: from 1 - very ...
29,absences,int64,Numerical,24,number of school absences (numeric: from 0 to 93)
30,G1,int64,Numerical,17,first period grade (numeric: from 0 to 20)
31,G2,int64,Numerical,16,second period grade (numeric: from 0 to 20)
32,G3,int64,Numerical,17,"final grade (numeric: from 0 to 20, output tar..."

In [15]:
# ── 3.3  Summary of the dictionary ───────────────────────────────────

print("Category breakdown:")
print(data_dict["Category"].value_counts())

print("\nColumns with missing values:")
missing = data_dict[data_dict["Missing Values"] > 0][["Column Name", "Missing Values"]]
print(missing if not missing.empty else "None")

Category breakdown:
Category
Numerical               16
Binary (Categorical)    13
Categorical              4
Name: count, dtype: int64

Columns with missing values:
None

In [16]:
# ── 3.4  Type conversion — correcting the data matrix ─────────────────
# Some columns look numerical but are actually categorical.
# Example: 'Medu' (mother education 0-4) is ordinal, not continuous.

print("Before conversion:")
print(df[["school", "sex", "Medu", "Fedu"]].dtypes)

# Convert binary text columns to category
binary_cols = ["school", "sex", "address", "famsize", "Pstatus",
               "schoolsup", "famsup", "paid", "activities",
               "nursery", "higher", "internet", "romantic"]

for col in binary_cols:
    df[col] = df[col].astype("category")

# Convert ordinal columns to category
ordinal_cols = ["Medu", "Fedu", "traveltime", "studytime",
                "famrel", "freetime", "goout", "Dalc", "Walc", "health"]

for col in ordinal_cols:
    df[col] = df[col].astype("category")

print("\nAfter conversion:")
print(df[["school", "sex", "Medu", "Fedu"]].dtypes)

Before conversion:
school    object
sex       object
Medu       int64
Fedu       int64
dtype: object

After conversion:
school    category
sex       category
Medu      category
Fedu      category
dtype: object

In [17]:
# ── 3.5  Rebuild the dictionary after type correction ─────────────────

data_dict_v2 = pd.DataFrame({
    "Column Name"   : df.columns,
    "Data Type"     : df.dtypes.astype(str).values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values" : df.nunique().values,
    "Category"      : [classify_column(col) for col in df.columns],
    "Description"   : [variable_descriptions.get(col, "—") for col in df.columns]
})

print("Updated category breakdown after type correction:")
print(data_dict_v2["Data Type"].value_counts())
display(data_dict_v2)

Updated category breakdown after type correction:
Data Type
category    23
int64        6
object       4
Name: count, dtype: int64

,Column Name,Data Type,Missing Values,Unique Values,Category,Description
0,school,category,0,2,Other,student's school (binary: 'GP' - Gabriel Perei...
1,sex,category,0,2,Other,student's sex (binary: 'F' - female or 'M' - m...
2,age,int64,0,8,Numerical,student's age (numeric: from 15 to 22)
3,address,category,0,2,Other,student's home address type (binary: 'U' - urb...
4,famsize,category,0,2,Other,family size (binary: 'LE3' - less or equal to ...
5,Pstatus,category,0,2,Other,parent's cohabitation status (binary: 'T' - li...
6,Medu,category,0,5,Other,"mother's education (numeric: 0 - none, 1 - pr..."
7,Fedu,category,0,5,Other,"father's education (numeric: 0 - none, 1 - pr..."
8,Mjob,object,0,5,Categorical,"mother's job (nominal: 'teacher', 'health' car..."
9,Fjob,object,0,5,Categorical,"father's job (nominal: 'teacher', 'health' car..."
10,reason,object,0,4,Categorical,reason to choose this school (nominal: close t...
11,guardian,object,0,3,Categorical,"student's guardian (nominal: 'mother', 'father..."
12,traveltime,category,0,4,Other,home to school travel time (numeric: 1 - <15 m...
13,studytime,category,0,4,Other,"weekly study time (numeric: 1 - <2 hours, 2 - ..."
14,failures,int64,0,4,Numerical,number of past class failures (numeric: n if 1...
15,schoolsup,category,0,2,Other,extra educational support (binary: yes or no)
16,famsup,category,0,2,Other,family educational support (binary: yes or no)
17,paid,category,0,2,Other,extra paid classes within the course subject (...
18,activities,category,0,2,Other,extra-curricular activities (binary: yes or no)
19,nursery,category,0,2,Other,attended nursery school (binary: yes or no)
20,higher,category,0,2,Other,wants to take higher education (binary: yes or...
21,internet,category,0,2,Other,Internet access at home (binary: yes or no)
22,romantic,category,0,2,Other,with a romantic relationship (binary: yes or no)
23,famrel,category,0,5,Other,quality of family relationships (numeric: from...
24,freetime,category,0,5,Other,free time after school (numeric: from 1 - very...
25,goout,category,0,5,Other,going out with friends (numeric: from 1 - very...
26,Dalc,category,0,5,Other,workday alcohol consumption (numeric: from 1 -...
27,Walc,category,0,5,Other,weekend alcohol consumption (numeric: from 1 -...
28,health,category,0,5,Other,current health status (numeric: from 1 - very ...
29,absences,int64,0,24,Numerical,number of school absences (numeric: from 0 to 93)
30,G1,int64,0,17,Numerical,first period grade (numeric: from 0 to 20)
31,G2,int64,0,16,Numerical,second period grade (numeric: from 0 to 20)
32,G3,int64,0,17,Numerical,"final grade (numeric: from 0 to 20, output tar..."

### Exercise 3
Build a mini data dictionary for **only the target columns** `G1`, `G2`, `G3`:  
Include: Column Name, Data Type, Min, Max, Mean, and a one-line Description.

```python
# Hint:
# df["G1"].min(), df["G1"].max(), df["G1"].mean()
```

In [ ]:
# Your answer here

---
## Part 4 — Putting It All Together: Two Insights
Now that we understand the data types, the matrix, and the dictionary, we extract meaningful insights.

In [18]:
# ── Insight 1: Highest correlation between numerical columns ──────────

num_df   = df.select_dtypes(include=["int64", "float64"])
corr_mat = num_df.corr().abs()

# Remove self-correlations
np.fill_diagonal(corr_mat.values, np.nan)

highest_pair  = corr_mat.stack().idxmax()
highest_value = corr_mat.stack().max()

print(f" Insight 1 — Highest correlation:")
print(f"   '{highest_pair[0]}' and '{highest_pair[1]}' → r = {highest_value:.3f}")
print(f"   Interpretation: These two features are strongly related.")

 Insight 1 — Highest correlation:
   'G2' and 'G3' → r = 0.919
   Interpretation: These two features are strongly related.

In [19]:
# ── Insight 2: Average final grade by study time ──────────────────────

# Convert studytime back to int for groupby
avg_grade = df.copy()
avg_grade["studytime"] = avg_grade["studytime"].astype(int)

result = avg_grade.groupby("studytime")["G3"].mean().round(2)
result.index = result.index.map({
    1: "<2 hrs",
    2: "2–5 hrs",
    3: "5–10 hrs",
    4: ">10 hrs"
})

print(" Insight 2 — Average Final Grade (G3) by Weekly Study Time:")
print(result.to_string())
print("\n   Interpretation: Students who study more tend to score higher.")

 Insight 2 — Average Final Grade (G3) by Weekly Study Time:
studytime
<2 hrs      10.84
2–5 hrs     12.09
5–10 hrs    13.23
>10 hrs     13.06

   Interpretation: Students who study more tend to score higher.

---
## Summary

| Concept | What you learned |
|---|---|
| **Python Data Types** | `int`, `float`, `str`, `bool`, `list`, `dict` and how to cast between them |
| **Pandas dtypes** | `int64`, `float64`, `object`, `category` and how they map to Python types |
| **Data Matrix** | Rows = observations, Columns = features; how to access, slice, and describe it |
| **Missing Values** | How to detect them and measure their extent |
| **Data Dictionary** | How to build, enrich, and use a structured column reference table |
| **Type Correction** | Why converting columns to the right type matters for analysis |

---
### Final Exercise — Try on your own dataset!
1. Find any CSV dataset from [Kaggle](https://www.kaggle.com) or [UCI](https://archive.ics.uci.edu)
2. Load it and print the shape
3. Identify numerical, categorical, and missing columns
4. Build a full data dictionary with descriptions
5. Convert at least two columns to the correct type
6. Extract two meaningful insights

**Bring your notebook to the next session for discussion! 🚀**